version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - $PWD:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
  accolli:
    image: docker.io/luckysideburn/cartediaccollo:latest
    environment:
    - MONGO_HOST=mongodb
    ports:
    - 5000:5000
    volumes:
    -  $PWD/cards:/usr/src/app/static/cards
